replicaCount: 1

image:
  repository: laurencebel/cast-service
  pullPolicy: Always
  tag: "v.22.0"

name: "cast-service"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000

command:
  - sh
  - '-c'
  - uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

env:
  - name: DATABASE_URI
    value: "postgresql://cast_db_username:cast_db_password@cast-db/cast_db_dev"

serviceAccount:
  create: false
  annotations: {}
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
